/// Build script for smooth-pearls: compiles the DoltLite amalgamation
/// when the `doltlite` feature is enabled.
///
/// DoltLite is a SQLite fork with Prolly Tree storage and git-style
/// version control. The amalgamation (sqlite3.c) is a single C file
/// generated by `./configure && make` in the doltlite submodule. It
/// contains all of SQLite + Prolly Tree engine + DoltLite extensions.
///
/// Pre-requisite: run `cd crates/smooth-pearls/doltlite && ./configure && make`
/// once to generate the amalgamation. This is analogous to how
/// libsqlite3-sys bundles stock SQLite.

fn main() {
    #[cfg(feature = "doltlite")]
    build_doltlite();
}

#[cfg(feature = "doltlite")]
fn build_doltlite() {
    let root = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("doltlite");
    let amalgamation = root.join("sqlite3.c");

    if !amalgamation.exists() {
        panic!(
            "DoltLite amalgamation not found at {}. \
             Run: cd crates/smooth-pearls/doltlite && ./configure && make",
            amalgamation.display()
        );
    }

    cc::Build::new()
        .file(&amalgamation)
        .include(&root) // sqlite3.h, sqlite_cfg.h, parse.h, etc.
        .include(root.join("src")) // sqliteInt.h and friends
        .include(root.join("ext").join("fts3"))
        .include(root.join("ext").join("rtree"))
        .include(root.join("ext").join("session"))
        .include(root.join("ext").join("rbu"))
        .include(root.join("ext").join("icu"))
        .warnings(false)
        // DoltLite Prolly Tree engine
        .define("DOLTLITE_PROLLY", "1")
        .define("DOLTLITE_VERSION", "\"v0.3.8\"")
        // Standard SQLite flags matching libsqlite3-sys bundled defaults
        .define("SQLITE_CORE", None)
        .define("SQLITE_DEFAULT_FOREIGN_KEYS", "1")
        .define("SQLITE_ENABLE_API_ARMOR", None)
        .define("SQLITE_ENABLE_COLUMN_METADATA", None)
        .define("SQLITE_ENABLE_FTS3", None)
        .define("SQLITE_ENABLE_FTS3_PARENTHESIS", None)
        .define("SQLITE_ENABLE_FTS5", None)
        .define("SQLITE_ENABLE_JSON1", None)
        .define("SQLITE_ENABLE_MATH_FUNCTIONS", None)
        .define("SQLITE_ENABLE_MEMORY_MANAGEMENT", None)
        .define("SQLITE_ENABLE_PERCENTILE", None)
        .define("SQLITE_ENABLE_RTREE", None)
        .define("SQLITE_ENABLE_STAT4", None)
        .define("SQLITE_ENABLE_UPDATE_DELETE_LIMIT", None)
        .define("SQLITE_ENABLE_UNLOCK_NOTIFY", None)
        .define("SQLITE_ENABLE_PREUPDATE_HOOK", None)
        .define("SQLITE_ENABLE_SESSION", None)
        .define("SQLITE_SOUNDEX", None)
        .define("SQLITE_THREADSAFE", "1")
        .define("SQLITE_HAVE_ZLIB", "1")
        .define("HAVE_USLEEP", "1")
        .define("HAVE_LOCALTIME_R", "1")
        .define("HAVE_ISNAN", "1")
        .define("NDEBUG", None)
        .flag_if_supported("-O2")
        .compile("doltlite");

    let out_dir = std::env::var("OUT_DIR").unwrap();
    println!("cargo:rustc-link-search=native={out_dir}");
    println!("cargo:rustc-link-lib=static=doltlite");
    println!("cargo:rustc-link-lib=z");

    // Tell libsqlite3-sys to NOT build its own bundled SQLite — we provide it.
    println!("cargo:sqlite3={}", root.display());

    println!("cargo:rerun-if-changed=doltlite/sqlite3.c");
    println!("cargo:rerun-if-changed=doltlite/sqlite3.h");
    println!("cargo:rerun-if-changed=build.rs");
}
