//! Streaming "thoughts" for Big Smooth's chat-agent — short first-person
//! one-liners summarizing each tool call / assistant turn, generated by
//! the Fast slot (Gemini Flash Lite). Surfaced over the WebSocket so the
//! chat UI can render floating thought bubbles next to the face and make
//! the agent's work feel alive instead of opaque.
//!
//! The summarizer is non-blocking: the main agent loop never waits on
//! it. Concurrency is capped by a Semaphore so a long burst of tool
//! calls doesn't stampede the gateway.

use std::sync::Arc;

use smooth_operator::conversation::Message;
use smooth_operator::llm::LlmClient;
use smooth_operator::providers::{Activity, ProviderRegistry};
use tokio::sync::Semaphore;

use crate::events::ServerEvent;

/// Cap concurrent Gemini Flash Lite calls in flight at once. Four lets
/// a burst of tool-call events surface as bubbles in tight succession
/// without the chat-agent's own iterations overrunning the summarizer.
/// Two was too tight — bursts of 4-5 tool calls produced bubbles
/// staggered over several seconds.
const MAX_INFLIGHT: usize = 4;

/// One in-flight summarizer with shared rate-limit state.
#[derive(Clone)]
pub struct ThoughtStreamer {
    client: Option<Arc<LlmClient>>,
    permits: Arc<Semaphore>,
    event_tx: tokio::sync::broadcast::Sender<ServerEvent>,
}

impl ThoughtStreamer {
    /// Build a streamer that resolves the Fast slot from the registry.
    /// If the slot can't be resolved (no `fast` route configured) the
    /// returned streamer is a no-op — callers don't need to branch.
    pub fn new(registry: &ProviderRegistry, event_tx: tokio::sync::broadcast::Sender<ServerEvent>) -> Self {
        let client = match registry.llm_config_for(Activity::Fast) {
            Ok(cfg) => Some(Arc::new(LlmClient::new(cfg))),
            Err(e) => {
                tracing::warn!("ThoughtStreamer: no Fast slot configured ({e}); thought stream disabled");
                None
            }
        };
        Self {
            client,
            permits: Arc::new(Semaphore::new(MAX_INFLIGHT)),
            event_tx,
        }
    }

    /// Queue a thought for the given action context. Returns immediately
    /// — actual summarization happens on a background tokio task.
    pub fn emit(&self, context: ThoughtContext) {
        let Some(client) = self.client.clone() else { return };
        let permits = self.permits.clone();
        let tx = self.event_tx.clone();
        tokio::spawn(async move {
            // Drop summary if we can't acquire a permit fast — better
            // to skip a thought than queue a stale one.
            let Ok(permit) = permits.try_acquire_owned() else { return };
            let prompt = context.into_prompt();
            let req = [Message::system(SYSTEM_PROMPT), Message::user(prompt)];
            let req_refs: Vec<&Message> = req.iter().collect();
            match client.chat(&req_refs, &[]).await {
                Ok(resp) => {
                    let cleaned = clean_thought(&resp.content);
                    if !cleaned.is_empty() {
                        let _ = tx.send(ServerEvent::BigSmoothThought { text: cleaned });
                    }
                }
                Err(e) => tracing::debug!("thought summarizer failed: {e}"),
            }
            drop(permit);
        });
    }
}

/// Inputs to the summarizer — kept as a small enum so we can shape the
/// prompt per kind. (A tool call needs a different framing than a
/// streamed assistant text snippet.)
pub enum ThoughtContext {
    ToolCall {
        tool_name: String,
    },
    AssistantPreview {
        snippet: String,
    },
    /// Heartbeat thought — emitted on a periodic timer while a long
    /// tool call (teammate_wait, big search) is in flight, so the UI
    /// bubbles keep flowing and the user can see BS is still alive.
    Heartbeat {
        last_action: String,
        seconds: u32,
    },
}

impl ThoughtContext {
    fn into_prompt(self) -> String {
        match self {
            Self::ToolCall { tool_name } => {
                format!(
                    "I'm about to run my tool `{tool_name}`. In one short sentence (≤ 8 words, present tense, first person), describe what I'm doing right now. No quotes, no list, no emoji.\n\nExample tools and good summaries:\n- pearls_search → \"Skimming the pearl board for matches…\"\n- pearls_create → \"Filing a fresh pearl for this work…\"\n- teammate_spawn → \"Bringing a teammate online for the job…\"\n- teammate_wait → \"Watching for the teammate to land…\"\n- teammate_read → \"Reading what the teammate came back with…\"\n- teammate_message → \"Nudging the teammate with new context…\"\n\nRespond with ONLY the one-line thought."
                )
            }
            Self::AssistantPreview { snippet } => {
                let clipped: String = snippet.chars().take(280).collect();
                format!(
                    "I just thought to myself: \"{clipped}\". Compress that into one short first-person sentence (≤ 8 words, present tense). No quotes, no list, no emoji. Respond with ONLY the one-line thought."
                )
            }
            Self::Heartbeat { last_action, seconds } => {
                format!(
                    "I'm still working on my last action: `{last_action}`. It's been {seconds} seconds. In one short, varied sentence (≤ 8 words, present tense, first person), describe what I'm doing right now to keep the user informed. No quotes, no list, no emoji. Examples: \"Still waiting on the teammate to chime in…\", \"Holding tight while the search finishes…\", \"Letting the operator cook for a moment…\". Respond with ONLY the one-line thought."
                )
            }
        }
    }
}

const SYSTEM_PROMPT: &str = "You are the inner monologue of an AI agent named Big Smooth. \
Your job is to convert the agent's actions and intermediate plans into one short, \
first-person, present-tense thought (≤ 8 words). Be vivid but calm. Never use quotes, \
markdown, lists, or emoji. Just the thought itself, no preamble.";

/// Strip common LLM frill (leading bullets, trailing punctuation noise,
/// surrounding quotes) and clip to a hard length cap so a chatty model
/// can't dominate the bubble row.
fn clean_thought(raw: &str) -> String {
    let mut s = raw.trim().to_string();
    // Strip surrounding matching quotes (one pass — Gemini sometimes
    // double-quotes the answer even after we ask it not to).
    if let (Some(first), Some(last)) = (s.chars().next(), s.chars().last()) {
        if (first == '"' && last == '"') || (first == '\'' && last == '\'') {
            let mut chars = s.chars();
            chars.next();
            chars.next_back();
            s = chars.collect();
        }
    }
    // Strip leading list markers / bullets, char-aware so we don't
    // panic on multi-byte glyphs like `•`.
    loop {
        let first = s.chars().next();
        match first {
            Some('-' | '*' | '•') => {
                let mut chars = s.chars();
                chars.next();
                s = chars.as_str().trim_start().to_string();
            }
            _ => break,
        }
    }
    // Collapse newlines into a single space — bubbles are one-line.
    let s = s.split_whitespace().collect::<Vec<_>>().join(" ");
    // Hard cap.
    if s.chars().count() > 80 {
        s.chars().take(80).collect::<String>() + "…"
    } else {
        s
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn clean_strips_quotes_and_bullets() {
        assert_eq!(clean_thought("\"Searching pearls\""), "Searching pearls");
        assert_eq!(clean_thought("- Spawning a teammate"), "Spawning a teammate");
        assert_eq!(clean_thought("  • Reading the result  "), "Reading the result");
    }

    #[test]
    fn clean_clips_long_text() {
        let long: String = "a".repeat(200);
        let out = clean_thought(&long);
        assert!(out.chars().count() <= 81);
        assert!(out.ends_with('…'));
    }

    #[test]
    fn clean_collapses_whitespace() {
        assert_eq!(clean_thought("hello\n\nworld"), "hello world");
    }
}
