//! Long-running `smooth-dolt serve` companion + Unix-socket client.
//!
//! Background: calling `PearlStore::open` from inside a Big Smooth tokio
//! handler reliably wedges the spawned `smooth-dolt sql` subprocess in
//! `pthread_cond_wait` and never returns. The same operation from a TTY
//! finishes in 50ms; the second open inside the same Rust process is
//! what's broken (see pearl `th-1a61a7` for the full investigation). This
//! module sidesteps the issue by replacing the spawn-per-call pattern
//! with a long-running `smooth-dolt serve <data-dir> --socket <path>`
//! subprocess that opens the Dolt database once and answers JSON-line
//! queries over a Unix socket.
//!
//! `SmoothDoltServer` owns the spawned process and exposes
//! [`SmoothDoltServer::client`] which returns a fresh `SmoothDoltClient`
//! connected to the socket. Clients can issue many requests sequentially
//! on a single connection. The server child is killed and the socket
//! file is removed on `Drop`.

use std::io::{BufRead, BufReader, Write};
use std::os::unix::net::UnixStream;
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Mutex;
use std::time::{Duration, Instant};

use anyhow::{anyhow, Context, Result};
use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::dolt::{find_smooth_dolt_binary, find_smooth_dolt_launcher_binary};

/// Wallclock timeout applied to every request/response on a client
/// connection. Without this, a wedged `smooth-dolt serve` (e.g. after
/// macOS overnight sleep) can leave the calling thread blocked
/// indefinitely on `read_line`. With it, callers see a timeout error
/// quickly and the self-heal path on the server side can respawn.
const CLIENT_OP_TIMEOUT: Duration = Duration::from_secs(15);

/// Background health-check probe timeout. Keep this aggressive — a
/// healthy server pings in <5ms; we want to give up fast and respawn.
const HEALTH_PROBE_TIMEOUT: Duration = Duration::from_secs(3);

/// Shell-escape a single argument by wrapping it in single quotes and
/// escaping any embedded single quotes. Sufficient for our use (paths
/// generated by Rust, no funny chars), keeps the shell string readable
/// in error messages.
fn shell_escape(s: &str) -> String {
    let escaped = s.replace('\'', r"'\''");
    format!("'{escaped}'")
}

/// How long to wait for the spawned server to create its socket file
/// before giving up. Cold-start of the embedded Dolt engine on a
/// reasonably fast machine is sub-second; we give it a generous cap.
/// Bumped to 30s after observing smoo-hub repeatedly hit the old 15s
/// ceiling under load.
const SERVER_START_TIMEOUT: Duration = Duration::from_secs(30);

/// On retry after a failed spawn, scrub any zombie `smooth-dolt serve`
/// processes for this data dir before trying again — sometimes the
/// previous run left a half-stuck child holding the database lock.
fn kill_stale_serve_for(data_dir: &Path) {
    let needle = match data_dir.canonicalize() {
        Ok(p) => p.to_string_lossy().to_string(),
        Err(_) => data_dir.to_string_lossy().to_string(),
    };
    // Best-effort. We use pgrep+kill rather than parsing /proc — this
    // path runs on macOS too, and the failure modes (no pgrep, no
    // matches) are all silent.
    let out = Command::new("pgrep")
        .arg("-f")
        .arg(format!("smooth-dolt serve {needle}"))
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .output();
    if let Ok(out) = out {
        let pids = String::from_utf8_lossy(&out.stdout);
        for pid in pids.split_whitespace() {
            tracing::warn!(data_dir = %needle, pid = %pid, "killing stale smooth-dolt serve");
            let _ = Command::new("kill").arg("-9").arg(pid).status();
        }
    }
}

/// Held inside a `Mutex` on `SmoothDoltServer` so we can swap the
/// child + socket atomically when the server gets respawned. (The
/// `tempfile::TempDir` lives here too so the socket directory is
/// cleaned up at drop time.)
#[derive(Debug)]
struct ServerHandle {
    socket: PathBuf,
    child: Option<Child>,
    /// Held to clean up the socket directory on drop. Replaced wholesale
    /// when the server is respawned so the old socket gets unlinked.
    _socket_dir: tempfile::TempDir,
}

/// Long-running `smooth-dolt serve` subprocess + the Unix socket it's
/// listening on. Created once per dolt data directory; clients open
/// fresh connections per call via [`SmoothDoltServer::client`].
///
/// **Single-writer queue.** Every higher-level op (`sql`, `exec`,
/// `commit`) goes through [`SmoothDoltServer::with_client`], which
/// acquires `serial_lock` for the duration of the call. Two callers
/// to the same data dir are serialized — they cannot race each other
/// into the Dolt manifest lock. Combined with (a) the 15 s socket
/// read/write timeout, (b) the connect-time self-heal in `client()`,
/// and (c) the 30 s background healthcheck respawn loop, this is the
/// full set of safeguards against the failure modes Dolt-as-a-daemon
/// exhibits: cold-start delays, manifest contention, and macOS-sleep
/// goroutine wedges.
#[derive(Debug)]
pub struct SmoothDoltServer {
    /// Source-of-truth dir for the dolt database. Kept so the server
    /// can self-respawn without external coordination.
    data_dir: PathBuf,
    /// Latest server child + socket. Locked under a sync `Mutex`
    /// because callers (including blocking SmoothDolt::commit paths)
    /// don't always have an async runtime in scope.
    inner: Mutex<ServerHandle>,
    /// Single-writer serializer. Every public op acquires this for
    /// its full duration so two callers can't race each other into
    /// the Dolt manifest lock. Separate from `inner` because we want
    /// `respawn` (which writes to `inner`) to be able to grab the
    /// lock briefly without contending with itself.
    serial_lock: Mutex<()>,
}

impl SmoothDoltServer {
    /// Spawn `smooth-dolt serve` for the given data dir, retrying once
    /// (after killing any stale `smooth-dolt serve` for the same dir)
    /// if the first attempt times out. The retry is the self-heal path
    /// for the recurring "did not create socket within …" failure
    /// where a half-dead previous server is squatting on the database.
    ///
    /// # Errors
    /// Fails when the `smooth-dolt` binary can't be located or both
    /// spawn attempts time out / the server fails to respond.
    pub fn spawn(data_dir: &Path) -> Result<Self> {
        let handle = match Self::spawn_handle_once(data_dir) {
            Ok(h) => h,
            Err(first) => {
                tracing::warn!(data_dir = %data_dir.display(), error = %first, "smooth-dolt spawn failed; killing zombies and retrying once");
                kill_stale_serve_for(data_dir);
                std::thread::sleep(Duration::from_millis(500));
                Self::spawn_handle_once(data_dir).with_context(|| format!("smooth-dolt spawn retry also failed (first attempt: {first:#})"))?
            }
        };
        Ok(Self {
            data_dir: data_dir.to_path_buf(),
            inner: Mutex::new(handle),
            serial_lock: Mutex::new(()),
        })
    }

    /// Run `f` against a fresh client connection while holding the
    /// single-writer serializer. Use this for every dolt op — it's
    /// the supported entry point for callers that want serialization.
    /// `client()` exposed below is the lower-level path that doesn't
    /// serialize (used internally by `is_healthy`, where we WANT
    /// concurrency with in-flight work so we can detect a wedge).
    ///
    /// # Errors
    /// Surfaces both the `client()` connect/respawn errors and any
    /// errors `f` returns from its op.
    pub fn with_client<F, T>(&self, f: F) -> Result<T>
    where
        F: FnOnce(&mut SmoothDoltClient) -> Result<T>,
    {
        let _guard = self.serial_lock.lock().expect("dolt serial_lock poisoned");
        let mut client = self.client()?;
        f(&mut client)
    }

    /// One spawn attempt — blocks until the socket is ready (or
    /// `SERVER_START_TIMEOUT` elapses). Internal helper for
    /// [`SmoothDoltServer::spawn`], which wraps it with a self-heal
    /// retry path.
    fn spawn_handle_once(data_dir: &Path) -> Result<ServerHandle> {
        let bin = find_smooth_dolt_binary().context("smooth-dolt binary not found. Run: scripts/build-smooth-dolt.sh")?;

        let socket_dir = tempfile::Builder::new().prefix("smooth-dolt-").tempdir().context("create socket tempdir")?;
        let socket = socket_dir.path().join("dolt.sock");

        // Spawn through `smooth-dolt-launcher` if available — a tiny
        // C wrapper that resets the inherited signal mask, closes
        // every fd > 2, and `setsid`s before exec'ing smooth-dolt.
        // This matters when the parent is a long-running Tokio
        // process (Big Smooth): without the launcher, Go's runtime
        // in the child wedges on first SQL query because Tokio has
        // installed signal masks (Go needs SIGURG for goroutine
        // preemption) and Go grabs leftover Tokio epoll fds at
        // startup. The launcher is roughly 30 lines of C; see
        // `c/smooth-dolt-launcher/launcher.c` for the full
        // rationale.
        //
        // When the launcher binary isn't available (e.g. a stripped
        // dev install), we fall back to the shell-laundered spawn
        // which is enough for short-lived parents like `th` CLI but
        // doesn't reliably work from inside BS.
        let launcher = find_smooth_dolt_launcher_binary();
        let mut cmd = if let Some(ref launcher_bin) = launcher {
            let mut c = Command::new(launcher_bin);
            c.arg(&bin).arg("serve").arg(data_dir).arg("--socket").arg(&socket);
            c
        } else {
            let serve_cmdline = format!(
                "exec {} serve {} --socket {}",
                shell_escape(&bin.to_string_lossy()),
                shell_escape(&data_dir.to_string_lossy()),
                shell_escape(&socket.to_string_lossy()),
            );
            let mut c = Command::new("/bin/sh");
            c.arg("-c").arg(&serve_cmdline);
            c
        };
        cmd.stdin(Stdio::null())
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .env_clear()
            .env("PATH", "/usr/bin:/bin:/usr/local/bin:/opt/homebrew/bin")
            .env("HOME", std::env::var("HOME").unwrap_or_default());

        let child = cmd
            .spawn()
            .with_context(|| format!("spawn smooth-dolt serve via {}", launcher.as_ref().map_or("shell", |_| "smooth-dolt-launcher")))?;

        // Wait for the server to create its socket file.
        let deadline = Instant::now() + SERVER_START_TIMEOUT;
        while !socket.exists() {
            if Instant::now() >= deadline {
                // Ensure we don't leak the half-started child.
                let mut zombie = child;
                let _ = zombie.kill();
                let _ = zombie.wait();
                anyhow::bail!("smooth-dolt serve did not create socket within {:?}", SERVER_START_TIMEOUT);
            }
            std::thread::sleep(Duration::from_millis(50));
        }

        let handle = ServerHandle {
            socket: socket.clone(),
            child: Some(child),
            _socket_dir: socket_dir,
        };

        // Verify the server is actually responding before returning.
        let mut probe = SmoothDoltClient::connect(&socket).context("connect to freshly-spawned smooth-dolt serve")?;
        probe.ping().context("ping freshly-spawned smooth-dolt serve")?;
        drop(probe);

        Ok(handle)
    }

    /// Path to the Unix socket the server is currently listening on.
    /// May change over the server's lifetime if it self-heals — call
    /// each time rather than caching.
    pub fn socket_path(&self) -> PathBuf {
        let inner = self.inner.lock().expect("dolt server mutex poisoned");
        inner.socket.clone()
    }

    /// Open a fresh client connection. Many can coexist; the server
    /// handles each connection on its own goroutine.
    ///
    /// On connection failure (typically a stale socket from a child
    /// that died or was paused-then-killed during macOS sleep) we
    /// respawn the child and retry once. Callers see a single retry
    /// of latency; subsequent calls hit the fresh server normally.
    ///
    /// # Errors
    /// Fails only if both the initial connection AND the post-respawn
    /// connection fail.
    pub fn client(&self) -> Result<SmoothDoltClient> {
        let socket = self.socket_path();
        match SmoothDoltClient::connect(&socket) {
            Ok(c) => Ok(c),
            Err(e) => {
                tracing::warn!(socket = %socket.display(), error = %e, "smooth-dolt client connect failed; attempting self-heal respawn");
                self.respawn().context("respawn smooth-dolt during client() self-heal")?;
                let socket = self.socket_path();
                SmoothDoltClient::connect(&socket).with_context(|| format!("connect to respawned smooth-dolt at {}", socket.display()))
            }
        }
    }

    /// Run a quick ping with `HEALTH_PROBE_TIMEOUT`. Returns `Ok(())`
    /// when the server answers, `Err` when it's gone or wedged.
    pub fn is_healthy(&self) -> Result<()> {
        let socket = self.socket_path();
        let mut client = SmoothDoltClient::connect_with_timeout(&socket, HEALTH_PROBE_TIMEOUT).context("health: connect")?;
        client.ping().context("health: ping")
    }

    /// Probe the server; if it's not healthy, respawn it. Idempotent
    /// — safe to call from a periodic background task.
    pub fn ensure_healthy(&self) -> Result<()> {
        if self.is_healthy().is_ok() {
            return Ok(());
        }
        tracing::warn!(data_dir = %self.data_dir.display(), "smooth-dolt server unhealthy — respawning");
        self.respawn().context("ensure_healthy: respawn")?;
        self.is_healthy().context("ensure_healthy: post-respawn ping")
    }

    /// Kill the current child (if any) and start a fresh one. The
    /// inner handle is replaced atomically.
    fn respawn(&self) -> Result<()> {
        // Try to spawn a NEW handle first; only swap in once it's
        // verified healthy. This way a transient spawn failure
        // doesn't take the server permanently offline.
        let new_handle = match Self::spawn_handle_once(&self.data_dir) {
            Ok(h) => h,
            Err(first) => {
                kill_stale_serve_for(&self.data_dir);
                std::thread::sleep(Duration::from_millis(500));
                Self::spawn_handle_once(&self.data_dir)
                    .with_context(|| format!("respawn smooth-dolt for {}: retry also failed (first: {first:#})", self.data_dir.display()))?
            }
        };
        let mut inner = self.inner.lock().expect("dolt server mutex poisoned");
        // Drop-replace the old handle: takes the old child + tempdir,
        // SIGTERMs the child via ServerHandle's drop semantics below.
        let old = std::mem::replace(&mut *inner, new_handle);
        drop(old); // explicit so the SIGTERM happens before we return
        Ok(())
    }
}

impl Drop for ServerHandle {
    fn drop(&mut self) {
        if let Some(mut child) = self.child.take() {
            // SIGTERM equivalent — the Go server handles it cleanly,
            // unlinks its socket file, and exits.
            let _ = child.kill();
            let _ = child.wait();
        }
        // tempfile::TempDir cleanup runs after this; if the server
        // forgot to remove its socket, that takes care of it.
    }
}

/// One open connection to a [`SmoothDoltServer`]. Each request gets a
/// monotonically-increasing correlation id so test/debug paths can
/// distinguish responses.
pub struct SmoothDoltClient {
    stream: UnixStream,
    reader: BufReader<UnixStream>,
    next_id: AtomicU64,
}

#[derive(Serialize)]
struct ServerRequest<'a> {
    id: String,
    op: &'a str,
    #[serde(skip_serializing_if = "Option::is_none")]
    query: Option<&'a str>,
    #[serde(skip_serializing_if = "Option::is_none")]
    stmt: Option<&'a str>,
    #[serde(skip_serializing_if = "Option::is_none")]
    message: Option<&'a str>,
    #[serde(skip_serializing_if = "Option::is_none")]
    limit: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    cmd: Option<&'a str>,
}

#[derive(Deserialize)]
struct ServerResponse {
    /// Echo of the request id. Currently unused on the client side
    /// (we read responses synchronously per request), but kept so
    /// debug logs and future pipelined transports can match up
    /// requests and responses.
    #[serde(default)]
    #[allow(dead_code)]
    id: String,
    ok: bool,
    #[serde(default)]
    error: String,
    #[serde(default)]
    data: Vec<Value>,
    #[serde(default)]
    out: String,
    #[serde(default)]
    rows_affected: i64,
}

impl SmoothDoltClient {
    /// Connect to a `smooth-dolt serve` Unix socket. Applies the
    /// default `CLIENT_OP_TIMEOUT` to read/write so a wedged server
    /// can't block the caller indefinitely.
    ///
    /// # Errors
    /// Returns the underlying I/O error if the socket can't be opened.
    pub fn connect(socket: &Path) -> Result<Self> {
        Self::connect_with_timeout(socket, CLIENT_OP_TIMEOUT)
    }

    /// Like [`connect`] but with a caller-chosen timeout — used by the
    /// server's own health-check path which wants to give up faster.
    pub fn connect_with_timeout(socket: &Path, timeout: Duration) -> Result<Self> {
        let stream = UnixStream::connect(socket).with_context(|| format!("connect {}", socket.display()))?;
        // Apply read/write timeouts so a wedged peer surfaces as an
        // io::Error rather than blocking the calling thread forever.
        let _ = stream.set_read_timeout(Some(timeout));
        let _ = stream.set_write_timeout(Some(timeout));
        let reader_stream = stream.try_clone().context("clone unix stream for reader")?;
        let _ = reader_stream.set_read_timeout(Some(timeout));
        let reader = BufReader::new(reader_stream);
        Ok(Self {
            stream,
            reader,
            next_id: AtomicU64::new(1),
        })
    }

    /// Liveness check.
    pub fn ping(&mut self) -> Result<()> {
        let _ = self.send(ServerRequest {
            id: self.next_id(),
            op: "ping",
            query: None,
            stmt: None,
            message: None,
            limit: None,
            cmd: None,
        })?;
        Ok(())
    }

    /// Run a SELECT and parse rows as JSON values.
    ///
    /// # Errors
    /// Returns the server's reported error (or a transport failure).
    pub fn sql(&mut self, query: &str) -> Result<Vec<Value>> {
        let resp = self.send(ServerRequest {
            id: self.next_id(),
            op: "sql",
            query: Some(query),
            stmt: None,
            message: None,
            limit: None,
            cmd: None,
        })?;
        Ok(resp.data)
    }

    /// Run a non-SELECT statement.
    ///
    /// # Errors
    /// Returns the server's reported error (or a transport failure).
    pub fn exec(&mut self, stmt: &str) -> Result<i64> {
        let resp = self.send(ServerRequest {
            id: self.next_id(),
            op: "exec",
            query: None,
            stmt: Some(stmt),
            message: None,
            limit: None,
            cmd: None,
        })?;
        Ok(resp.rows_affected)
    }

    /// `dolt add -A && dolt commit -m <message> --allow-empty`.
    pub fn commit(&mut self, message: &str) -> Result<String> {
        let resp = self.send(ServerRequest {
            id: self.next_id(),
            op: "commit",
            query: None,
            stmt: None,
            message: Some(message),
            limit: None,
            cmd: None,
        })?;
        Ok(resp.out)
    }

    /// `dolt log -n <limit>` returning pre-formatted lines.
    pub fn log(&mut self, limit: usize) -> Result<String> {
        let resp = self.send(ServerRequest {
            id: self.next_id(),
            op: "log",
            query: None,
            stmt: None,
            message: None,
            limit: Some(limit),
            cmd: None,
        })?;
        Ok(resp.out)
    }

    /// One of the `dolt` no-arg commands: `push`, `pull`, `gc`, `status`.
    pub fn dolt(&mut self, cmd: &str) -> Result<String> {
        let resp = self.send(ServerRequest {
            id: self.next_id(),
            op: "dolt",
            query: None,
            stmt: None,
            message: None,
            limit: None,
            cmd: Some(cmd),
        })?;
        Ok(resp.out)
    }

    fn next_id(&self) -> String {
        format!("c-{}", self.next_id.fetch_add(1, Ordering::Relaxed))
    }

    fn send(&mut self, req: ServerRequest<'_>) -> Result<ServerResponse> {
        let mut bytes = serde_json::to_vec(&req).context("encode request")?;
        bytes.push(b'\n');
        self.stream.write_all(&bytes).context("write request")?;
        self.stream.flush().context("flush request")?;

        let mut line = String::new();
        let n = self.reader.read_line(&mut line).context("read response")?;
        if n == 0 {
            anyhow::bail!("smooth-dolt server closed connection");
        }
        let resp: ServerResponse = serde_json::from_str(line.trim_end()).with_context(|| format!("parse response: {line}"))?;
        if !resp.ok {
            return Err(anyhow!("smooth-dolt: {}", resp.error));
        }
        Ok(resp)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::AtomicUsize;
    use std::sync::Arc;
    use std::thread;

    /// `with_client` must serialize concurrent callers — at most one
    /// can be inside the closure at a time, even if many threads
    /// race in. This is the property that prevents Dolt manifest-
    /// lock contention between, e.g., the chat agent and a
    /// background commit.
    #[test]
    fn with_client_serializes_concurrent_callers() {
        let tmp = match tempfile::tempdir() {
            Ok(t) => t,
            Err(_) => return,
        };
        let dolt_dir = tmp.path().join("dolt");
        if crate::dolt::SmoothDolt::new(&dolt_dir).and_then(|d| d.init()).is_err() {
            return;
        }
        let server = match SmoothDoltServer::spawn(&dolt_dir) {
            Ok(s) => Arc::new(s),
            Err(_) => return,
        };

        // Counter rises while a caller is "inside" the closure and
        // falls when they leave. If serialization works, the high-
        // water mark stays at exactly 1 even with 8 racing threads.
        let inside = Arc::new(AtomicUsize::new(0));
        let high_water = Arc::new(AtomicUsize::new(0));

        let handles: Vec<_> = (0..8)
            .map(|_| {
                let server = server.clone();
                let inside = inside.clone();
                let high_water = high_water.clone();
                thread::spawn(move || {
                    server
                        .with_client(|client: &mut SmoothDoltClient| -> Result<()> {
                            let now = inside.fetch_add(1, Ordering::SeqCst) + 1;
                            high_water.fetch_max(now, Ordering::SeqCst);
                            // Hold the lock for a moment so contention is real.
                            std::thread::sleep(Duration::from_millis(20));
                            client.ping()?;
                            inside.fetch_sub(1, Ordering::SeqCst);
                            Ok(())
                        })
                        .expect("with_client succeeds");
                })
            })
            .collect();
        for h in handles {
            h.join().expect("thread");
        }
        assert_eq!(high_water.load(Ordering::SeqCst), 1, "with_client must serialize");
    }

    /// Spin up a server against a freshly-init'd dolt store and exercise
    /// the basic ops. Skips silently if `smooth-dolt` isn't built locally.
    #[test]
    fn server_roundtrip() {
        let tmp = match tempfile::tempdir() {
            Ok(t) => t,
            Err(_) => return,
        };
        let dolt_dir = tmp.path().join("dolt");

        // Initialize via the existing one-shot path.
        if crate::dolt::SmoothDolt::new(&dolt_dir).and_then(|d| d.init()).is_err() {
            // No binary or init failed — skip.
            return;
        }
        let dolt = crate::dolt::SmoothDolt::new(&dolt_dir).unwrap();
        // Create a tiny table so we have something to query.
        dolt.exec("CREATE TABLE IF NOT EXISTS smoke (id INT, label TEXT)").unwrap();
        dolt.exec("INSERT INTO smoke VALUES (1, 'hello'), (2, 'world')").unwrap();
        // Drop the one-shot handle so it doesn't hold any global resources.
        drop(dolt);

        let server = match SmoothDoltServer::spawn(&dolt_dir) {
            Ok(s) => s,
            Err(_) => return, // serve binary missing or spawn failed in CI
        };

        let mut client = server.client().expect("client");
        client.ping().expect("ping");

        let rows = client.sql("SELECT id, label FROM smoke ORDER BY id").expect("sql");
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0]["label"], "hello");
        assert_eq!(rows[1]["label"], "world");

        // Reuse the same connection for multiple queries.
        let count_rows = client.sql("SELECT COUNT(*) AS n FROM smoke").expect("count");
        assert_eq!(count_rows[0]["n"], 2);
    }
}
