name: Release (Changesets)

on:
    workflow_dispatch:
    push:
        branches:
            - main

env:
    CI: true

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    release:
        runs-on: ubuntu-latest
        timeout-minutes: 20
        permissions:
            contents: write
            pull-requests: write
            id-token: write
            actions: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GH_PAT }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
                  cache: 'pnpm'
                  registry-url: 'https://registry.npmjs.org'

            - name: Install dependencies
              run: pnpm install

            - name: Typecheck
              run: pnpm typecheck

            - name: Lint
              run: pnpm lint

            - name: Test
              run: pnpm test

            - name: Build
              run: pnpm build

            - name: Create Release PR or Publish
              id: changesets
              uses: changesets/action@v1
              with:
                  publish: pnpm changeset publish
                  commit: 'chore: version packages'
                  title: 'chore: version packages'
                  createGithubReleases: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_PAT }}
                  NPM_TOKEN: ${{ secrets.SMOOAI_NPM_TOKEN }}
